// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-matches.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_matches_default = defineTool({
  name: "search_matches",
  title: "Search upcoming matches",
  description: "Search upcoming football matches on Foot Ticket Finder. Filter by team name, city, competition, or country. Returns kickoff date, venue, teams, ticket status, and ticket link when available.",
  inputSchema: {
    query: z.string().trim().max(120).describe("Free-text search over team names, city, or competition.").optional(),
    country: z.string().trim().max(80).describe("Filter by country (e.g. 'England').").optional(),
    competition: z.string().trim().max(120).describe("Filter by competition (e.g. 'Premier League', 'FIFA World Cup 2026').").optional(),
    limit: z.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, country, competition, limit }, ctx) => {
    let q = supabaseFor(ctx).from("matches").select(
      "id,slug,date,home_team,away_team,stadium,city,country,competition,ticket_status,starting_price,ticombo_url,lifecycle_status,publication_status,archived_at"
    ).is("archived_at", null).eq("publication_status", "published").gte("date", (/* @__PURE__ */ new Date()).toISOString()).order("date", { ascending: true }).limit(limit ?? 15);
    if (country) q = q.ilike("country", `%${country}%`);
    if (competition) q = q.ilike("competition", `%${competition}%`);
    if (query) {
      const like = `%${query}%`;
      q = q.or(
        `home_team.ilike.${like},away_team.ilike.${like},city.ilike.${like},stadium.ilike.${like},competition.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((m) => ({
      id: m.id,
      slug: m.slug,
      kickoff: m.date,
      match: `${m.home_team} vs ${m.away_team}`,
      venue: `${m.stadium}, ${m.city}, ${m.country}`,
      competition: m.competition,
      ticket_status: m.ticket_status,
      starting_price: m.starting_price,
      tickets_url: m.ticombo_url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { matches: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-match.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_match_default = defineTool2({
  name: "get_match",
  title: "Get match details",
  description: "Return full details for a single match by its id or slug: teams, kickoff, stadium, competition, ticket status, provider link and starting price.",
  inputSchema: {
    match: z2.string().trim().min(1).max(200).describe("Match id or slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ match }, ctx) => {
    const sb = supabaseFor2(ctx);
    const byId = await sb.from("matches").select(
      "id,slug,date,home_team,away_team,home_short,away_short,stadium,city,country,competition,phase,group_code,ticket_status,starting_price,ticombo_url,official_link,lifecycle_status,publication_status,archived_at"
    ).or(`id.eq.${match},slug.eq.${match}`).is("archived_at", null).maybeSingle();
    if (byId.error)
      return { content: [{ type: "text", text: byId.error.message }], isError: true };
    if (!byId.data)
      return {
        content: [{ type: "text", text: `No match found for '${match}'.` }],
        isError: true
      };
    return {
      content: [{ type: "text", text: JSON.stringify(byId.data, null, 2) }],
      structuredContent: { match: byId.data }
    };
  }
});

// src/lib/mcp/tools/search-stadiums.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_stadiums_default = defineTool3({
  name: "search_stadiums",
  title: "Search stadiums",
  description: "Search football stadiums by name, city or country. Returns capacity, coordinates, resident clubs and Foot Ticket Finder slug.",
  inputSchema: {
    query: z3.string().trim().max(120).describe("Free-text search over stadium name, city, aliases.").optional(),
    country: z3.string().trim().max(80).describe("Filter by country.").optional(),
    world_cup_host: z3.boolean().describe("If true, only return 2026 World Cup host stadiums.").optional(),
    limit: z3.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, country, world_cup_host, limit }, ctx) => {
    let q = supabaseFor3(ctx).from("stadiums").select("id,slug,name,city,country,capacity,latitude,longitude,clubs,is_world_cup_host").is("archived_at", null).limit(limit ?? 15);
    if (country) q = q.ilike("country", `%${country}%`);
    if (world_cup_host === true) q = q.eq("is_world_cup_host", true);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`name.ilike.${like},city.ilike.${like},club_name.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { stadiums: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/tools/search-clubs.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseFor4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_clubs_default = defineTool4({
  name: "search_clubs",
  title: "Search football clubs",
  description: "Search football clubs in the Foot Ticket Finder catalog by name, league or country.",
  inputSchema: {
    query: z4.string().trim().max(120).describe("Free-text search over club name and aliases.").optional(),
    country: z4.string().trim().max(80).describe("Filter by country name.").optional(),
    limit: z4.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, country, limit }, ctx) => {
    let q = supabaseFor4(ctx).from("clubs").select("id,slug,name,display_name,short_name,country,league,city").is("archived_at", null).eq("publication_status", "published").limit(limit ?? 15);
    if (country) q = q.ilike("country", `%${country}%`);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`name.ilike.${like},display_name.ilike.${like},short_name.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clubs: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/tools/list-my-favorites.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseFor5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_favorites_default = defineTool5({
  name: "list_my_favorites",
  title: "List my saved matches",
  description: "List the matches the signed-in Foot Ticket Finder user has saved to their favorites, with kickoff, teams, venue and ticket status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseFor5(ctx);
    const { data: saved, error } = await sb.from("saved_matches").select("match_id,alerts_enabled,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!saved || saved.length === 0)
      return {
        content: [{ type: "text", text: "No saved matches yet." }],
        structuredContent: { matches: [] }
      };
    const ids = saved.map((s) => s.match_id);
    const { data: matches, error: mErr } = await sb.from("matches").select("id,slug,date,home_team,away_team,stadium,city,country,competition,ticket_status,ticombo_url").in("id", ids);
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const alertMap = new Map(saved.map((s) => [s.match_id, s.alerts_enabled]));
    const rows = (matches ?? []).map((m) => ({ ...m, alerts_enabled: alertMap.get(m.id) ?? false }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { matches: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/save-match.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseFor6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_match_default = defineTool6({
  name: "save_match",
  title: "Save match to favorites",
  description: "Save a match to the signed-in user's favorites on Foot Ticket Finder. Optionally enable ticket alerts for that match.",
  inputSchema: {
    match_id: z5.string().trim().min(1).max(120).describe("The match id (from search_matches / get_match)."),
    alerts_enabled: z5.boolean().default(true).describe("Enable ticket alerts for this match.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ match_id, alerts_enabled }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseFor6(ctx);
    const { data, error } = await sb.from("saved_matches").upsert(
      { user_id: ctx.getUserId(), match_id, alerts_enabled },
      { onConflict: "user_id,match_id" }
    ).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved match ${match_id}.` }],
      structuredContent: { saved: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "efhbpagnaaafdmvlwqbp";
var mcp_default = defineMcp({
  name: "foot-ticket-finder-mcp",
  title: "Foot Ticket Finder",
  version: "0.1.0",
  instructions: "Tools for Foot Ticket Finder \u2014 find upcoming football matches, stadiums and clubs, and manage the signed-in user's saved matches and ticket alerts. Public catalog data is readable by any authenticated user; user-specific tools act as the signed-in user through RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_matches_default, get_match_default, search_stadiums_default, search_clubs_default, list_my_favorites_default, save_match_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
