-- Backfill official crests for major clubs that are currently missing logos.
-- Uses football-data.org public crests CDN (already used for Paris FC).
UPDATE public.club_ticketing_profiles SET logo_url = v.logo, updated_at = now()
FROM (VALUES
  ('bayern-munich', 'https://crests.football-data.org/5.png'),
  ('fc-bayern-munchen', 'https://crests.football-data.org/5.png'),
  ('borussia-dortmund', 'https://crests.football-data.org/4.png'),
  ('fc-barcelona', 'https://crests.football-data.org/81.png'),
  ('barcelona', 'https://crests.football-data.org/81.png'),
  ('juventus', 'https://crests.football-data.org/109.png'),
  ('liverpool', 'https://crests.football-data.org/64.png'),
  ('liverpool-fc', 'https://crests.football-data.org/64.png'),
  ('manchester-city', 'https://crests.football-data.org/65.png'),
  ('manchester-united', 'https://crests.football-data.org/66.png'),
  ('olympique-de-marseille', 'https://crests.football-data.org/516.png'),
  ('olympique-marseille', 'https://crests.football-data.org/516.png'),
  ('marseille', 'https://crests.football-data.org/516.png'),
  ('paris-saint-germain', 'https://crests.football-data.org/524.png'),
  ('psg', 'https://crests.football-data.org/524.png'),
  ('real-madrid', 'https://crests.football-data.org/86.png'),
  ('real-madrid-cf', 'https://crests.football-data.org/86.png'),
  ('inter-milan', 'https://crests.football-data.org/108.png'),
  ('fc-internazionale-milano', 'https://crests.football-data.org/108.png'),
  ('ac-milan', 'https://crests.football-data.org/98.png'),
  ('atletico-madrid', 'https://crests.football-data.org/78.png'),
  ('atletico-de-madrid', 'https://crests.football-data.org/78.png'),
  ('chelsea', 'https://crests.football-data.org/61.png'),
  ('chelsea-fc', 'https://crests.football-data.org/61.png'),
  ('arsenal', 'https://crests.football-data.org/57.png'),
  ('arsenal-fc', 'https://crests.football-data.org/57.png'),
  ('tottenham', 'https://crests.football-data.org/73.png'),
  ('tottenham-hotspur', 'https://crests.football-data.org/73.png'),
  ('napoli', 'https://crests.football-data.org/113.png'),
  ('ssc-napoli', 'https://crests.football-data.org/113.png'),
  ('as-roma', 'https://crests.football-data.org/100.png'),
  ('roma', 'https://crests.football-data.org/100.png'),
  ('lazio', 'https://crests.football-data.org/110.png'),
  ('ss-lazio', 'https://crests.football-data.org/110.png'),
  ('benfica', 'https://crests.football-data.org/1903.png'),
  ('sl-benfica', 'https://crests.football-data.org/1903.png'),
  ('porto', 'https://crests.football-data.org/503.png'),
  ('fc-porto', 'https://crests.football-data.org/503.png'),
  ('ajax', 'https://crests.football-data.org/678.png'),
  ('afc-ajax', 'https://crests.football-data.org/678.png'),
  ('rb-leipzig', 'https://crests.football-data.org/721.png'),
  ('bayer-leverkusen', 'https://crests.football-data.org/3.png')
) AS v(slug, logo)
WHERE public.club_ticketing_profiles.slug = v.slug
  AND (public.club_ticketing_profiles.logo_url IS NULL OR public.club_ticketing_profiles.logo_url = '');